// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK1-q7DS1K4Q0vXdhpf8g2rf-o1Mvd5jc',
    appId: '1:564256902063:web:f2a16e6f139afbed1ebd5a',
    messagingSenderId: '564256902063',
    projectId: 'taqvo-uz',
    authDomain: 'taqvo-uz.firebaseapp.com',
    storageBucket: 'taqvo-uz.appspot.com',
    measurementId: 'G-G4T51HY6CS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzlgMP26j5W7VGzH0ZLPIqFG8rO6SWJyc',
    appId: '1:564256902063:android:868ed72a4111632a1ebd5a',
    messagingSenderId: '564256902063',
    projectId: 'taqvo-uz',
    storageBucket: 'taqvo-uz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_WbJFDamMcFe7DmAt6lgVVKS9elQG5CQ',
    appId: '1:564256902063:ios:5b7914faaa80a6f11ebd5a',
    messagingSenderId: '564256902063',
    projectId: 'taqvo-uz',
    storageBucket: 'taqvo-uz.appspot.com',
    iosClientId: '564256902063-o7ie4vs28nse3ponlo31g1ipmb50rj9d.apps.googleusercontent.com',
    iosBundleId: 'com.pdp.iymanUz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_WbJFDamMcFe7DmAt6lgVVKS9elQG5CQ',
    appId: '1:564256902063:ios:5b7914faaa80a6f11ebd5a',
    messagingSenderId: '564256902063',
    projectId: 'taqvo-uz',
    storageBucket: 'taqvo-uz.appspot.com',
    iosClientId: '564256902063-o7ie4vs28nse3ponlo31g1ipmb50rj9d.apps.googleusercontent.com',
    iosBundleId: 'com.pdp.iymanUz',
  );
}
